AUTH_MODE = "PASSWORD"  # or "AUTH0"
APP_PASSWORD = "ChangeMe"  # dev default; can be overridden by a secret
COMPANY_LOGO_URL = "https://raw.githubusercontent.com/TheMarketingScientist/brandliftmvp/main/logo.png"
